
project_id = "libyrenaizrhzbxiigjv"
[functions.process-deepseek-question]
verify_jwt = true
[functions.process-pdf-question]
verify_jwt = true
[functions.process-poe-question]
verify_jwt = true

[functions.send-study-reminder]
schedule = "*/5 * * * *"
verify_jwt = false

